name: C++ Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Ubuntu deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Install macOS deps
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Install Windows deps
        if: matrix.os == 'windows-latest'
        run: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y

      - run: cmake -E make_directory build
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: hello-${{ matrix.os }}
          path: build/

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hello-ubuntu-latest/**
            hello-windows-latest/**
            hello-macos-latest/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}