name: C++ Build & Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Install CMake (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Install CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-${{ matrix.os }}
          path: |
            build/Release/hello
            build/Release/hello.exe